#! /bin/bash
sudo apt install wget
cd ~/Downloads
wget https://developer.nvidia.com/downloads/embedded/l4t/r32_release_v7.5/t210/jetson-210_linux_r32.7.5_aarch64.tbz2
wget https://developer.nvidia.com/downloads/embedded/l4t/r32_release_v7.5/t210/tegra_linux_sample-root-filesystem_r32.7.5_aarch64.tbz2
sudo tar -jxpf ./jetson-210_linux_r32.7.5_aarch64.tbz2
cd ./Linux_for_Tegra/rootfs
sudo tar -jxpf ./tegra_linux_sample-root-filesystem_r32.7.5_aarch64.tbz2
cp .dtb ./kernel/dtb/
cd ../
sudo apply_binaries.sh
sudo BOOTDEV=mmcblk1p1 ./flash.sh --external_device jetson-nano-emmc mmcblk1p1
